name: geo-spatial-frontpage-app
region: fra
domains:
  - domain: rua1.com.br
    type: PRIMARY
    minimum_tls_version: "1.2"
  - domain: www.rua1.com.br
    type: ALIAS
    minimum_tls_version: "1.2"
services:
  - name: geo-spatial-frontpage
    environment_slug: node-js
    github:
      repo: pyunc/geo-spatial-frontpage
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm run build
    run_command: npm run start
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
ingress:
  rules:
    - match:
        authority:
          exact: www.rua1.com.br
      redirect:
        authority: rua1.com.br
        scheme: https
        redirect_code: 308
    - match:
        authority:
          exact: ${STARTER_DOMAIN}
      redirect:
        authority: rua1.com.br
        scheme: https
        redirect_code: 308
    - match:
        path:
          prefix: /
      component:
        name: geo-spatial-frontpage
